layout_spectrum: 0.9382979
description: Portfólio
name: lrnco
title: Luciano Liranço
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
navigation:
  - url: 'http://lrnco.cc'
    name: Luciano Liranço
    type: external
typography_spectrum: 0.1851064
color:
  brandStrength: 0.8638794810976833
  lightness: 0.01489362
  saturation: 0.7404255
  rhythmicContrast: 0.1851064
